export enum ErrorKeys {
  GENERAL_SERVER_ERROR = "Some sort of undiagnosed error occured.",
  USER_NOT_AUTHORIZED = "You are not authorized to do this.",
  INVALID_REQUEST = "Your request is not valid. It is either missing required information or in the wrong format.",
  RATE_LIMIT_EXCEEDED = "Bro, slow down. I'm rate limiting you.",
  VALIDATION_ERROR = "There was an error while validating your request.",
  AUTHENTICATION_FAILED = "Your request failed to authenticate.",
  RESOURCE_NOT_FOUND = "I did not find what you are requesting.",
  METHOD_NOT_ALLOWED = "You're not allowed to use that HTTP method on this endpoint.",
  ACCESS_DENIED = "Nah, dog.  Nah.",
  MONSTER_TYPE_NOT_FOUND = "No such monster type supported.",
  STAT_TYPE_NOT_FOUND = "No such stat type supported.",
  SESSION_INVALID = "That session is invalid. Please log in again.",
  EMAIL_TAKEN = "Please use a different email.",
  CREDENTIALS_INVALID = "Could not log in.",
  CREDENTIALS_MISSING = "Could not log in due to missing credentials.",
  USERNAME_TAKEN = "Please use a different username.",
  TOKEN_MISSING = "You don't seem to have been logged in in the first place.",
  TOKEN_INVALID = "Your login token is not valid.",
  EMAIL_REQUIRED = "Please enter an email address.",
  RESET_TOKEN_EXPIRED = "This password reset token has expired.",

  // The following are for logging only, not user facing.
  EMAIL_INVALID = "Could not log in due to invalid email.", 
  SESSION_MISSING = "There is no such session as this.",
}